### ISSUE TITLE
Tracking issue for Kusama Parachains Launch 

### ISSUE THREAD

**Issue by thanhtung6824** [polkafoundry/newpolka#24]
### **Phase 1** : Crowdloan Strategy & Testing
We will choose between starting the Crowdloan campaign on-chain or on RedKite.

- [x] Crowdloan pallet : https://github.com/polkafoundry/newpolka/pull/17
- [x] Crowdloan UI for community testing
- [x] Crowdloan campaign on Redkite

### **Phase 2**: Prelaunch Canary Network
A set of pallets will deploy on Canary Network when Parachain features open
- [x]  Staking pallet : https://github.com/polkafoundry/newpolka/pull/25
- [ ] Token pallet: https://github.com/paritytech/polkadot-sdk/issues/327
- [x] Treasury pallet: paritytech/substrate#26 
- [x] Deploy to Halongbay Testnet

### **Phase 3**: Auctions - Parachain
- [x]  Join the auction
- [ ]  Explorer, wallet, document, ...
- [ ]  All the IDO run on RedKite will be deployed to PolkaSmith
- [ ]  Programs to recruit collators
- [ ]  Launch some Dapps
- [ ]  User portal
