### ISSUE TITLE
PolkaSmith v0.0.1 Release Checklist

### ISSUE THREAD

**Issue by thanhtung6824** [polkafoundry/newpolka#29]
This is the release checklist for PolkaSmith v0.0.1. All following
checks should be completed before publishing a new release of the
PolkaSmith runtime.

### Runtime Releases

- [x] Update frontier 
- [x]  Update substrate
- [x]  Intergrate chain bridge
- [x]  Determine chain spec
- [x]  Determine final values for crowdloan
- [x]  Update decimals to 18
- [ ]  Add token to treasury to pay for stakers
- [ ]  Slasher punishment
- [ ]  Intergrate chain link

### Client Releases

- [ ]  Update polkadotjs app
- [ ]  Explorer
- [ ]  Telemetry
